# Generated by Django 4.0 on 2021-12-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_booked',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
