# Generated by Django 4.0 on 2021-12-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
