# Generated by Django 4.0 on 2021-12-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0002_feature_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.CharField(max_length=100)),
                ('dishtitle', models.CharField(max_length=100000)),
                ('dishdesc', models.CharField(max_length=1000000)),
            ],
        ),
    ]
